openapi: 3.0.3
info:
  title: Dummy Items API
  description: "Partial OpenAPI definition for a dummy items sample. Only edit and modify the paths—everything else is not deployed."
  version: 1.0.0

paths:
  /items:
    get:
      summary: List all items
      description: Retrieves a list of dummy items.
      responses:
        "200":
          description: Items retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas.yml#/components/schemas/Item"
    post:
      summary: Create a new item
      description: Creates a new dummy item and returns it.
      requestBody:
        description: Item to create
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas.yml#/components/schemas/ItemCreate"
      responses:
        "201":
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: "./schemas.yml#/components/schemas/Item"

  /items/{itemId}:
    get:
      summary: Get item by ID
      description: Retrieves a single item by its ID.
      parameters:
        - name: itemId
          in: path
          description: ID of the item to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Item retrieved successfully
          content:
            application/json:
              schema:
                $ref: "./schemas.yml#/components/schemas/Item"
        "404":
          description: Item not found

    put:
      summary: Update an existing item
      description: Updates the details of an existing item by ID.
      parameters:
        - name: itemId
          in: path
          description: ID of the item to update
          required: true
          schema:
            type: string
      requestBody:
        description: Updated item payload
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas.yml#/components/schemas/ItemUpdate"
      responses:
        "200":
          description: Item updated successfully
          content:
            application/json:
              schema:
                $ref: "./schemas.yml#/components/schemas/Item"
        "404":
          description: Item not found

    delete:
      summary: Delete an item
      description: Deletes an existing item by its ID.
      parameters:
        - name: itemId
          in: path
          description: ID of the item to delete
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Item deleted successfully
        "404":
          description: Item not found
